version: '2'
services:
  web1:
    build:
      context: .docker/web
      dockerfile: Dockerfile-php-7.0
    container_name: devweb2
    ports:
      - "8080:80"
    links:
      - redis:devcache1
    volumes:
      - ./web/html:/var/www/html
  redis:
    build: .docker/cache
    container_name: devcache1